/*
CREATE TABLE MEMBERS (
    UserId VARCHAR2(50) NOT NULL,
    Password VARCHAR2(100) NOT NULL,
    UserName VARCHAR2(100),
    TeamName VARCHAR2(100),
    IsLocked NUMBER(1) DEFAULT 0,
    LoginAttempts NUMBER(10) DEFAULT 0,
    RegDate DATE DEFAULT SYSDATE,
    PRIMARY KEY (UserId)
);
*/
--DROP TABLE MEMBERS;

/*
CREATE TABLE CHATROOM(
	RoomId NUMBER NOT NULL,
	RoomName VARCHAR2(100) NOT NULL,
	RegTime TIMESTAMP DEFAULT SYSTIMESTAMP,
	RegId VARCHAR2(50) NOT NULL,
	PRIMARY KEY (RoomId),
	CONSTRAINT fk_RegId_Room FOREIGN KEY (RegId) REFERENCES MEMBERS(UserId)
);
*/
--DROP TABLE CHATROOM;

/*
CREATE TABLE MESSAGE (
    MsgId NUMBER PRIMARY KEY,
    RegId VARCHAR2(50) NOT NULL,
    RoomId NUMBER NOT NULL,
    Content VARCHAR2(1000),
    Image BLOB,
    RegTime TIMESTAMP DEFAULT SYSTIMESTAMP,
    IsDeleted NUMBER(1) DEFAULT 0,
    CONSTRAINT fk_RegId_Msg FOREIGN KEY (RegId) REFERENCES MEMBERS(UserId),
    CONSTRAINT fk_RoomId_Msg FOREIGN KEY (RoomId) REFERENCES CHATROOM(RoomId)
);
*/
--DROP TABLE MESSAGE;

/*
CREATE TABLE JOINROOM(
	UserId VARCHAR2(50) NOT NULL,
	RoomId NUMBER NOT NULL,
	CONSTRAINT fk_UserId_Join FOREIGN KEY (UserId) REFERENCES MEMBERS(UserId),
    CONSTRAINT fk_RoomId_Join FOREIGN KEY (RoomId) REFERENCES CHATROOM(RoomId)
);
*/
--DROP TABLE JOINROOM;
